TourOperator/Controllers/BookingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TourOperator.Mappings;
using TourOperator.Models;
using TourOperator.Services.DtoModels;
using TourOperator.Services.Interfaces;
using TourOperator.ViewModels;

namespace TourOperator.Controllers
{
    [Authorize]
    public class BookingController : Controller
    {
        private IBookingService _bookingService { get; set; }
        private IHotelService _hotelService { get; set; }
        private IHotelTypeService _hotelTypeService { get; set; }

        public BookingController(IHotelService hotelService, IHotelTypeService hotelTypeService, IBookingService bookingService)
        {
            _hotelService = hotelService;
            _hotelTypeService = hotelTypeService;
            _bookingService = bookingService;

        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Create(int HotelId)
        {
            var choosenHotel = _hotelService.GetHotelById(HotelId);
            var bookingViewModel = new BookingViewModel();

            bookingViewModel.Hotel = choosenHotel.ToHotelBookingModel();
            bookingViewModel.HotelId = choosenHotel.Id;

            return View(bookingViewModel);
        }
        [AllowAnonymous]
        [HttpPost]
        public IActionResult Create(BookingViewModel booking)
        {
            if (ModelState.IsValid)
            {
                var domainModel = booking.ToBookingDomainModel();
                domainModel.BookingCode = _bookingService.RandomGenerator(6);
                var response = _bookingService.CreateBooking(domainModel);

                var bookingResult = new BookingResult();
                bookingResult.IsSuccessful = response.IsSuccessful;
                bookingResult.Code = domainModel.BookingCode;


                if (response.IsSuccessful)
                {
                    bookingResult.Message = "Booking created sucessfully";
                    return RedirectToAction("BookingResult", bookingResult);
                }
                else
                {
                    bookingResult.Message = response.Message;
                    return RedirectToAction("BookingResult", bookingResult);
                }
            }

            return View(booking);
        }
        [AllowAnonymous]
        public IActionResult BookingResult(BookingResult bookingResult)
        {
            return View(bookingResult);
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult CheckBooking(string statusMessage)
        {
            ViewBag.StatusMessage = statusMessage;
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public IActionResult CheckBooking(CheckBooking checkBooking)
        {
       
            var checkBookingDomain = checkBooking.ToCheckBookingDomainModel();
            var booking = new Booking();

            booking = _bookingService.GetBookingByProperties(checkBookingDomain);

            

            if (booking == null)
            {
                return RedirectToAction("CheckBooking", new { StatusMessage = "Booking not found. Please try again" });
            }

            var bookingViewModel = booking.ToBookingViewModel();

            return RedirectToAction("BookingStatus", bookingViewModel);
        }
        [AllowAnonymous]
        public IActionResult BookingStatus(BookingViewModel bookingViewModel)
        {
            return View(bookingViewModel);
        }
        [Authorize(Roles = "Admin,CustomerSupport")]
        public IActionResult Overview()
        {
            var bookings = _bookingService.GetAllBookings();

            var bookingViewDataModel = new BookingViewDataModel();

            var bookingViewModels = bookings.Select(x => x.ToBookingViewModel()).ToList();
            bookingViewDataModel.OverviewBookings = bookingViewModels;
            return View(bookingViewDataModel);
        }
        [Authorize(Roles = "Admin,CustomerSupport")]
        public IActionResult ChangeStatus(int id)
        {
            var booking = _bookingService.GetBookingById(id);

            var status = booking.BookingStatus;

            if (status)
            {
                booking.BookingStatus = false;
            }
            else
            {
                booking.BookingStatus = true;
            }

            var response = _bookingService.Update(booking);

            var bookingResult = new BookingResult();
            bookingResult.IsSuccessful = response.IsSuccessful;
            bookingResult.Code = null;


            if (response.IsSuccessful)
            {
                bookingResult.Message = "Booking status changed sucessfully";
                return RedirectToAction("BookingResult", bookingResult);
            }
            else
            {
                bookingResult.Message = response.Message;
                return RedirectToAction("BookingResult", bookingResult);
            }

           
        }

    }
}

TourOperator/Controllers/HotelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TourOperator.Mappings;
using TourOperator.Services.Interfaces;
using TourOperator.ViewModels;

namespace TourOperator.Controllers
{
    public class HotelController : Controller
    {
        private IHotelService _hotelService { get; set; }
        private IHotelTypeService _hotelTypeService { get; set; }

    public HotelController(IHotelService hotelService,IHotelTypeService hotelTypeService)
        {
            _hotelService = hotelService;
            _hotelTypeService = hotelTypeService;

        }

        [AllowAnonymous]
        public IActionResult Overview(string name)
        {
            var hotels = _hotelService.GetHotelsWithFilters(name);

            var hotelOverviewDataModel = new HotelOverviewDataModel();

            var hotelOverviewModels = hotels.Select(x => x.ToOverviewModel()).ToList();
            hotelOverviewDataModel.OverviewHotels = hotelOverviewModels;
            return View(hotelOverviewDataModel);
        }
        [Authorize(Roles = "Admin,ContentCreator")]
        public IActionResult ManageOverview(string errorMessage, string successMessage)
        {
            ViewBag.ErrorMessage = errorMessage;
            ViewBag.SuccessMessage = successMessage;
            var hotels = _hotelService.GetAllHotels();

            var viewModels = hotels.Select(x => x.ToHotelMangeOverviewModel()).ToList();

            return View(viewModels);
        }
        [Authorize(Roles = "Admin,ContentCreator")]
        [HttpGet]
        public IActionResult Create()
        {
            var hotelTypes = _hotelTypeService.GetAll();
            var viewModels = hotelTypes.Select(x => x.ToHotelTypeModel()).ToList();

            var viewModel = new HotelCreateModel();
            viewModel.HotelTypes = viewModels;

            return View(viewModel);
        }
        [Authorize(Roles = "Admin,ContentCreator")]
        [HttpPost]
        public IActionResult Create(HotelCreateModel hotel)
        {
            if (ModelState.IsValid)
            {
                var domainModel = hotel.ToHotelDomainModel();
                var response = _hotelService.CreateHotel(domainModel);

                if (response.IsSuccessful)
                {
                    var userId = User.FindFirst("Id");
                  
                    return RedirectToAction("ManageOverview", new { SuccessMessage = "Hotel created sucessfully" });
                }
                else
                {
                    return RedirectToAction("ManageOverview", new { ErrorMessage = response.Message });
                }
            }

            var hotelTypes = _hotelTypeService.GetAll();
            var viewModels = hotelTypes.Select(x => x.ToHotelTypeModel()).ToList();

            hotel.HotelTypes = viewModels;

            return View(hotel);
        }
        [Authorize(Roles = "Admin,ContentCreator")]
        [AllowAnonymous]
        public IActionResult AdminDetails(int id)
        {
            try
            {
                var hotel = _hotelService.GetHotelById(id);

                if (hotel == null)
                {
                    return RedirectToAction("ErrorNotFound", "Info");
                }

                var hotelDetailsModel = hotel.ToHotelDetailsModel();

                
                return View(hotelDetailsModel);
            }
            catch (Exception)
            {
                return RedirectToAction("InternalError", "Info");
            }
        }
       
        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            try
            {
                var hotel = _hotelService.GetHotelById(id);

                if (hotel == null)
                {
                    return RedirectToAction("ErrorNotFound", "Info");
                }

                var hotelDetailsModel = hotel.ToHotelDetailsModel();


                return View(hotelDetailsModel);
            }
            catch (Exception)
            {
                return RedirectToAction("InternalError", "Info");
            }
        }


        [Authorize(Roles = "Admin,ContentCreator")]
        public IActionResult Delete(int id)
        {
            try
            {
                var response = _hotelService.Delete(id);

                if (response.IsSuccessful)
                {
                    return RedirectToAction("ManageOverview", new { SuccessMessage = "Hotel deleted sucessfully" });
                }
                else
                {
                    return RedirectToAction("ManageOverview", new { ErrorMessage = response.Message });
                }
            }
            catch (Exception)
            {
                return RedirectToAction("InternalError", "Info");
            }
        }
        [Authorize(Roles = "Admin,ContentCreator")]
        [HttpGet]
        public IActionResult Update(int id)
        {
            var hotel = _hotelService.GetHotelById(id);

            if (hotel == null)
            {
                return RedirectToAction("ManageOverview", new { ErrorMessage = "Hotel not found" });
            }

            var viewModel = hotel.ToHotelUpdateModel();

            var recipeTypes = _hotelTypeService.GetAll();
            var viewModels = recipeTypes.Select(x => x.ToHotelTypeModel()).ToList();

            viewModel.HotelTypes = viewModels;

            return View(viewModel);
        }
        [Authorize(Roles = "Admin,ContentCreator")]
        [HttpPost]
        public IActionResult Update(HotelUpdateModel hotel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var response = _hotelService.Update(hotel.ToHotelDomainModel());

                    if (response.IsSuccessful)
                    {
                        return RedirectToAction("ManageOverview", new { SuccessMessage = "Hotel updated successfuly" });
                    }
                    else
                    {
                        return RedirectToAction("ManageOverview", new { ErrorMessage = response.Message });
                    }
                }
                catch (Exception)
                {
                    return RedirectToAction("InternalError", "Info");
                }
            }

            return View(hotel);
        }



    }
}

TourOperator/Views/Hotel/AdminDetails.cshtml
@model TourOperator.ViewModels.HotelDetailsModel

@{
    ViewData["Title"] = "AdminDetails";
}

<h1> Admin Details</h1>

<div>
    <h4>HotelDetailsModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pool)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pool)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MiniBar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MiniBar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HotelTypeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HotelTypeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Views)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Views)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Update", "Update", new {  id = Model.Id }) |
    <a asp-action="Overview">Back to List</a>
</div>

TourOperator/Views/Hotel/Create.cshtml
@model TourOperator.ViewModels.HotelCreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Hotel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Pool" /> @Html.DisplayNameFor(model => model.Pool)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Bar" /> @Html.DisplayNameFor(model => model.Bar)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="MiniBar" /> @Html.DisplayNameFor(model => model.MiniBar)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="HotelTypeId" class="control-label"></label>
                <select asp-for ="HotelTypeId" class="form-control">
                    @foreach (var hotelType in Model.HotelTypes)
                    {
                        <option value="@hotelType.Id">@hotelType.Name</option>
                    }
                    </select>
</div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Overview">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TourOperator/Views/Hotel/Details.cshtml
@model TourOperator.ViewModels.HotelDetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>HotelDetailsModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pool)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pool)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MiniBar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MiniBar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HotelTypeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HotelTypeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Views)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Views)
        </dd>
    </dl>
</div>

    <div class="card-body">
        <a asp-controller="Booking" asp-action="Create" asp-route-hotelId="@Model.Id"> Go to Booking</a>
    </div>

TourOperator/Views/Hotel/ManageOverview.cshtml
@model IEnumerable<TourOperator.ViewModels.HotelManageOverviewModel>

@{
    ViewData["Title"] = "ManageOverview";
}

<h1>ManageOverview</h1>


@if (ViewBag.ErrorMessage != null)
{
    <div class="alert alert-danger" role="alert">
        @ViewBag.ErrorMessage
    </div>
}

@if (ViewBag.SuccessMessage != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.SuccessMessage
    </div>
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Update", "Update", new { id=item.Id }) |
                    @Html.ActionLink("AdminDetails", "AdminDetails", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

TourOperator/Views/Hotel/Overview.cshtml
@model TourOperator.ViewModels.HotelOverviewDataModel

@{
    ViewData["Title"] = "Overview";
}

<h1>Overview</h1>




<form action="/Hotel/Overview" method="get" style="width:500px" class="form-inline m-4">
    <div class="form-group">
        <input type="text" name="Name" value="" class="form-control" placeholder="Search by title" />
        <input type="submit" value="Search" class="btn btn-primary" />
    </div>
</form>



<div class="card-group">

    @foreach (var item in Model.OverviewHotels)
    {
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="@item.ImageUrl" alt="Hotel Image">

        <div class="card-body">
            <h5 class="card-title">@item.Name</h5>
            <p class="card-title">@item.Destination</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Price @item.Price <i class="fas fa-euro-sign"></i> </li>
            <li class="list-group-item">@item.HotelType</li>
            <li class="list-group-item">Views: @item.Views</li>
        </ul>
        <div class="card-body">
            <a asp-controller="Hotel" asp-action="Details" asp-route-id="@item.Id">Details</a>
        </div>
    </div>


        
    }
</div>

TourOperator/Views/Hotel/Update.cshtml
@model TourOperator.ViewModels.HotelUpdateModel

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>HotelUpdateModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Destination" class="control-label"></label>
                <input asp-for="Destination" class="form-control" />
                <span asp-validation-for="Destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Pool" /> @Html.DisplayNameFor(model => model.Pool)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Bar" /> @Html.DisplayNameFor(model => model.Bar)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="MiniBar" /> @Html.DisplayNameFor(model => model.MiniBar)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HotelTypeId" class="control-label"></label>
                <select asp-for="HotelTypeId" class="form-control">
                    @foreach (var hotelType in Model.HotelTypes)
                    {
                        <option value="@hotelType.Id">@hotelType.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Overview">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}